# Generated by Django 3.0.5 on 2020-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField(max_length=20)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
    ]
